database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "admin"
  name: "trackbox"
  ssl_mode: "disable"

kafka:
  host: "localhost"
  port: 9092
  tracking_updated_topic_name: "tracking.updated"

redis:
  host: "localhost"
  port: 6379

trackbox:
  grpc_addr: ":50051"
  http_addr: ":8080"
  kafka_consumer_group: "track-api"
  current_status_ttl_seconds: 600
  worker_poll_interval_seconds: 2
  worker_batch_size: 100
  worker_concurrency: 10
  worker_lease_seconds: 120
  worker_rate_limit_per_minute: 120
  carrier_emulator_base_url: "http://localhost:9000"
  carrier_emulator_mode: "track24"
  carrier_emulator_api_key: "demo-key"
  carrier_emulator_domain: "localhost"


